### ISSUE TITLE
Demo doesnt recovery 2020 year data

### ISSUE THREAD

**Issue by beuleal** [schme16/Chart.js-RangeSlider#3]
According the demo:
https://jsfiddle.net/schme16/xfyvvup8/20/

I cant retrive back the last value, example 2020 year data.  To get it, i need to reset init to [0,20], and then the 2020 year data is showed. After slide to less than 2020, the 2020 year data disapear. What is happend?

**Comment by ghost** [comment]
in RangeSlider-core.js _create-function: remove the -1 from the end of the 'max' attribute.

**Comment by Lambik** [comment]
Could the core be adapted to not have this -1? It seems an error? Or am I missing something, because I too would expect to be able to see the last datapoint when the slider is at max.

**Comment by beuleal** [comment]
@Lambik I did the changes myself... I would like see the developer looking for us. :( :-1:

**Comment by schme16** [comment]
This should be all sorted out now; open a new issue if you feel it's not resolved your issue :)

@johanvonboer: Theres a weird edge case where it can throw an error by trying to go past the end of the array, in some circumstances; The fix I've made looks super dumb, but resolves that issue.
