### ISSUE TITLE
chartType only provides a line chart

### ISSUE THREAD

**Issue by clone1524524** [schme16/Chart.js-RangeSlider#7]
In the description, it seems to indicate that other chart types are available:
chartType: 'Line', //Which Chart.js chart you want (eg. Lie, Bar, Pie, etc.)

Changing this variable appears to have no affect on the actual chart type. Is this intended?

**Comment by Morpheine** [comment]
I was experiencing this same issue earlier today, but I discovered the solution. Rather than using chartType, instead simply use type.

```
 ctx = document.getElementById("testChart").getContext('2d');
            myChart = new RangeSliderChart({
                type: 'bar',
                chartData: { },
                chartOpts: { },
                chartCTX: ctx,
                class: 'my-chart-ranger',
                initial: [0,100]
            });
```
Hope this helps!

**Comment by clone1524524** [comment]
I should have probably thought of that after looking through how RangeSlider-core.js refers to 'type', but I missed it. Good catch!

**Comment by schme16** [comment]
Would it help if I added a alias from chartType to type?

**Comment by Morpheine** [comment]
I think it would be worthwhile just to ensure that your aliases are consistent. :) I felt the same way when I put in class and initial as opposed to chartClass, etc. 

Is it feasible to re-write and eliminate the aliases on chartData, chartOpts and chartCTX instead, and return them to the default chartJS data, options and ctx? If so, then I think it may allow for your plugin to work a little cleaner for users who were modifying existing chartjs graphs. Just a suggestion, thanks for your hard work on this Schme16!
